# Grafana datasource configuration for Prometheus
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    uid: prometheus-uid
    jsonData:
      httpMethod: POST
      manageAlerts: true
      alertmanagerUid: alertmanager-uid
      prometheusType: Prometheus
      prometheusVersion: 2.48.1
      cacheLevel: 'High'
      disableRecordingRules: false
      incrementalQueryOverlapWindow: 10m
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: jaeger-uid
    secureJsonData:
      # Add authentication if needed
      # httpHeaderValue1: 'Bearer your-token'